### PR TITLE
Card background is now properly true black.

### PR DESCRIPTION
**Pull request by lance36**
A much needed commit.

### CODE REVIEW

**Comment by lance36** [comment]
I don't get why CI is failing, its fine my system

```$ yamllint -v
yamllint 1.15.0
$ yamllint .homeassistant/themes/amoled.yaml
.homeassistant/themes/amoled.yaml
  32:81     error    line too long (127 > 80 characters)  (line-length)
```

**Comment by maartenpaauw** [comment]
Travis CI error

  58:3      error    wrong ordering of key "ha-card-background" in mapping  (key-ordering)

**Comment by lance36** [comment]
I saw that. I don't get that error while running yamllint (1.20) on my system. So I'm not really sure what is wrong.

```$ yamllint /themes/amoled.yaml
.homeassistant/themes/amoled.yaml
  32:81     error    line too long (127 > 80 characters)  (line-length)

$ /yamllint -v
yamllint 1.20.0
```

**Comment by maartenpaauw** [comment]
Try to run `yamllint .`.

**Comment by lance36** [comment]
> Try to run `yamllint .`.

Dosen't change much, it just checks all the files in the current pwd...
I don't even understand the error given by CI, there's just a correctly formatted YAML line added:
`  ha-card-background: "#000000"`

**Comment by maartenpaauw** [comment]
Cool! I see you fixed the issue. Is it possible for you to rebase this branch (so I has 1 commit only)?

**Comment by lance36** [comment]
Fixed. Values needed to be sorted.
Ready to merge.

**Comment by lance36** [comment]
> 
> 
> Cool! I see you fixed the issue. Is it possible for you to rebase this branch (so I has 1 commit only)?

Like this? I'm not sure how to rebase it correctly

**Comment by lance36** [comment]
I'm just making a mess at this point, should i create a new PR? :|

**Pull request closed without merging**
